### ISSUE TITLE
OpenEXR install failed, I use http://www.excamera.com/sphinx/articles-openexr.html instead

### ISSUE THREAD

**Issue by yuanxy92** [gabrieleilertsen/hdrcnn#1]
pip install OpenEXR failed. (I use python3)

I install OpenEXR using easy_install:
 http://www.excamera.com/sphinx/articles-openexr.html

**Comment by nidetaoge** [comment]
Wow...Yuanxiao~

**Comment by jaisonoh** [comment]
Try unofficial OpenEXR binary for windows.
[https://www.lfd.uci.edu/~gohlke/pythonlibs/](https://www.lfd.uci.edu/~gohlke/pythonlibs/)

You can find OpenEXR whl file and download it.
And then, execute following python command for install whl

```python
python -m pip install OpenEXR-1.3.0-cp36-cp36m-win_amd64.whl
```

**Comment by zkailinzhang** [comment]
@jaisonoh , is there  OpenEXR whl for  ubuntu?
