### ISSUE TITLE
Question regarding the virtual camera.

### ISSUE THREAD

**Issue by ezaAlir** [gabrieleilertsen/hdrcnn#19]
Is the tone curve described in appendix A.3 in the paper applied separately to RGB color channels? or is it applied to the luminance?

Thanks.

**Comment by gabrieleilertsen** [comment]
Hi. The camera curve is applied separately to the RGB channels, [here](https://github.com/gabrieleilertsen/hdrcnn/blob/ae7d22146299ea3776aa6ad1edca0ad80743f5b5/training_code/virtualcamera/virtualcamera.cpp#L310).
