### ISSUE TITLE
How to transform the exr image sequences to HDR video with PQ/HLG standard? 

### ISSUE THREAD

**Issue by Hans1984** [gabrieleilertsen/hdrcnn#20]
Hi, thanks for your excellent work. And do you know is there any tools to transform the exr image sequences to HDR video with PQ/HLG standard. 
Thanks!

**Comment by gabrieleilertsen** [comment]
Hi! You can have a look at the [Luma HDRv](https://github.com/gabrieleilertsen/lumahdrv) repository. It can encode using PQ so that the video is compatible with applications that  support HDR10, and that can decode VP9 codec stored in a Matroska container.

**Comment by Hans1984** [comment]
Thanks! I'll try it.
