### ISSUE TITLE
Illegal instruction: 4 error

### ISSUE THREAD

**Issue by bbboy1901** [gabrieleilertsen/hdrcnn#21]
I'm very interested in testing this out, but I am getting "Illegal instruction: 4" error without traceback when I try to run the script.

I've seen similar errors listed in search results that indicate a problem with Tensorflow. Do you have a recommendation for which versions of the dependencies to have installed?

I'm working on a Mac with NVIDIA egpu so it's possible that is part of the problem.

I've tried it with Tensorflow version 1.1.0 (the last officially supported GPU version on Mac) as well as the CPU version of 1.6.

Thanks for your work on the project. LDR to HDR is a capability I've been hoping for.

**Comment by gabrieleilertsen** [comment]
I have tried some different versions between 1.1-1.8. I have tested on Mac too, but only on the CPU, so I'm not sure about this.

The question is if you get the error when you import TensorFlow, or if it happens somewhere else in the script.
