### ISSUE TITLE
Not getting hdr image

### ISSUE THREAD

**Issue by akashsahu410** [gabrieleilertsen/hdrcnn#22]
First image is getting dark and then it applying gamma filter on image.But on some image its not performing well.Please resolve.
Thanks

**Comment by gabrieleilertsen** [comment]
The PNGs that are produced are exported with reduced exposure and are gamma corrected, and are just 8-bit LDR images. These are meant for quick comparison between input and reconstructed image. The linear HDR reconstruction with no exposure correction is exported as EXR.

Some images are more difficult than others. For example, images with large saturated areas are more difficult. For information on what the reconstruction can and cannot do, please see the [paper](http://hdrv.org/hdrcnn/).
