### ISSUE TITLE
Using the encoder for anomaly detection

### ISSUE THREAD

**Issue by Tamoghna-Saha** [gabrieleilertsen/hdrcnn#23]
Hi,

I have run your model on multiple different images and it has given me perfect reconstruction every time. This led me to believe that the encoder model can be used directly for anomaly detection.

Is it possible for me to acquire the encoder weights for me to test this hypothesis?
Additionally, how should I modify your current codes with respect to the shape of the input/output and the exact line of codes that will require modification, etc?

Please let me know if you have any other ideas/hypothesis.

**Comment by gabrieleilertsen** [comment]
I am not sure I understand what you mean by "anomaly detection".

The weights are available for [download](http://hdrv.org/hdrcnn/material/hdrcnn_params.npz). Setting up the model and importing the weights as in the [prediction script](https://github.com/gabrieleilertsen/hdrcnn/blob/master/hdrcnn_predict.py), you can explore the weights or activations from each layer of the encoder for a certain image.
