### ISSUE TITLE
import OpenEXR, an error of undefined symbol _ZNK7Imf_2_214TypedAttributeISsE12writeValueToERNS_7OStreamEi

### ISSUE THREAD

**Issue by zkk0911** [gabrieleilertsen/hdrcnn#25]
import OpenEXR

ImportError: python3.5/site-packages/OpenEXR.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNK7Imf_2_214TypedAttributeISsE12writeValueToERNS_7OStreamEi

I work in linux server,and the OpenEXR has been installed successfully. There is an undefined symbol error when trying the command  ‘’python hdrcnn_predict.py xxx”.  Is there anyone met such issue, thanks

**Comment by ChuangbinC** [comment]
@zkk0911 Do you solve the problem? I have the same error.

**Comment by zkk0911** [comment]
no, It‘s really a problem, I try different python versions and building the OpenEXR sources and installing in different ways,  but it does‘t work

**Comment by ChuangbinC** [comment]
@zkk0911 I am sorry to ask you if you solve the problem again and could you give me your email so we can talk about this problem.

**Comment by ChuangbinC** [comment]
@zkk0911 Hi,I have solved this problem and reference to https://blog.csdn.net/qq_24306353/article/details/89111971

**Comment by zkk0911** [comment]
Thank you @ChuangbinC, I will try.
