### ISSUE TITLE
HDR to LDR

### ISSUE THREAD

**Issue by hhfzz** [gabrieleilertsen/hdrcnn#26]
Hi gabrieleilertsen, I am very interested in this article. My research content is the tonal mapping algorithm of HDR images. I want to try to use the training model in this article to achieve the conversion from HDR images to LDR images.Do you have any ideas or Suggestions?thank you.

**Comment by gabrieleilertsen** [comment]
Hi. Tone-mapping is a quite different problem. I have seen some attempts at deep learning for this purpose, but I'm not sure how well-suited it is for this setup. The main problem is to specify the ground truth tone-mapped images, for which some tone-mapping method is needed. Then, if that method is already available, why use deep learning to mimic it? An alternative is to have a number of possible tone-mappings for each HDR image, and select as ground truth the one with best performance according to some measure (e.g. [TMQI](https://ece.uwaterloo.ca/~z70wang/research/tmqi/)).

**Comment by hhfzz** [comment]
Thank you for your suggestion.
