### ISSUE TITLE
Training a new CNN weights?

### ISSUE THREAD

**Issue by frap129** [gabrieleilertsen/hdrcnn#3]
Hey there,

Is any code for training new CNN weights available? I can't find any documentation or relevant parameters. With the resent release of Googles HDR+ image set, I was hoping that I could possibly train my own weights to get more accurate reconstruction.

Thanks!

**Comment by gabrieleilertsen** [comment]
Hi. There has been many requests on training code, so I am planning to add this to the repository. However, I need to clean up the code and make it a bit more straightforward to use. I will try to find time for this during next week, so code is coming soon.

**Comment by frap129** [comment]
Thanks! I appreciate the hard work put into this
