### ISSUE TITLE
What is the version of tensorflow?

### ISSUE THREAD

**Issue by ghost** [gabrieleilertsen/hdrcnn#30]

**Comment by abekotaro** [comment]
What is the version of tensorflow?

**Comment by gabrieleilertsen** [comment]
I have used different versions, such as 1.8 and 1.11, but I don't see any problems in using other versions.

**Comment by abekotaro** [comment]
Thank you for your reply.
But hdrcnn_predict.py is executed

raceback (most recent call last):
   File "hdrcnn_predict.py", line 42, in <module>
     import tensorlayer as tl
   File "/usr/local/lib/python3.6/dist-packages/tensorlayer/__init__.py", line 27, in <module>
     "TensorLayer does not support Tensorflow version older than 2.0.0. \ N"
RuntimeError: TensorLayer does not support Tensorflow version older than 2.0.0.
Please update Tensorflow with:
  -`pip install --upgrade tensorflow`
  -`pip install --upgrade tensorflow-gpu`
I get an error.
Should Tensorflow version be newer than 2.0 to support TensorLayer?
I am using googlecolab

**Comment by gabrieleilertsen** [comment]
I don't know about the dependencies of Tensorlayer, but from your error message I guess you have to downgrade it to work with your Tensorflow install.

See e.g. [this issue](https://github.com/tensorlayer/openpose-plus/issues/203)
