### ISSUE TITLE
OpenEXR install for ubuntu in README

### ISSUE THREAD

**Issue by t2ac32** [gabrieleilertsen/hdrcnn#31]
> @siddas27  for ubuntu， sudo apt-get install openexr and libopenexr-dev before pip install solved it for me

> _Originally posted by @butterl in 

> https://github.com/gabrieleilertsen/hdrcnn/issues/5#issuecomment-394076616_

Could this be added to the main readme? 

For UBUNTU:
 sudo apt-get install openexr
 libopenexr-dev
 pip install OpenEXR

**Comment by gabrieleilertsen** [comment]
Thanks. Added a note about it in the install instructions.
