### ISSUE TITLE
The value range of HDR image in ground truth

### ISSUE THREAD

**Issue by ChuangbinC** [gabrieleilertsen/hdrcnn#33]
Hi, I find that the value range of the HDR image in ground truth set is seem no like absolute lumination in real world because the max value of the `img_0001.exr` is only 14.625. **What is it mean and what is the unit of the value?**

The ground trurh is from [this](http://hdrv.org/hdrcnn/material/testset/exr/ground_truth/)

Thanks!

**Comment by gabrieleilertsen** [comment]
Hi. There is no unit to the HDR values. The images are scaled to have a certain fraction of pixels larger that one. They are linearly dependent on luminance, i.e. for HDR image _I_ the luminance is _a*I_ cd/m2 for some unknown scaling factor _a_.

**Comment by ChuangbinC** [comment]
@gabrieleilertsen Thanks for your reply. And I have another question that whether you use some HDR reconstruction methods such as Debevec's to build your ground truth.

**Comment by gabrieleilertsen** [comment]
I used [hdrmerge](https://github.com/wjakob/hdrmerge) for the HDR images I captured myself (images 49-89 of the provided [testset](http://hdrv.org/hdrcnn/material/testset)). The other images, and training images, come from various online resources which were already merged.
