### ISSUE TITLE
Measure the reconstruction and the ground truth using HDR-VDP-2.2

### ISSUE THREAD

**Issue by PK15946** [gabrieleilertsen/hdrcnn#35]
Hi @gabrieleilertsen 
Can those reconstructed exr files directly compare with the ground truth exr files using HDR-VDP?  
I am trying to directly measure the reconstruction as followed
```
ref = hdrread('the exr ground truth in the provided testset')
tst = hdrread('your reconstruction exr file')
hdrvdp(tst,ref,'rgb-bt.709',30)
```
but the average Q score is much greater than it reported in [ExpandNet](https://onlinelibrary.wiley.com/doi/abs/10.1111/cgf.13340)(59 vs 41), I am not sure the result is right consider such a big difference.   Or, should I calibrate those exr file in absolute luminance BEFORE measuring them? like
`pfsin relative.exr | pfstmo_mantiuk08 -e 1 -d l=4000:b=0.01:a=0 | pfsdisplayfunction -d l=4000:b=0.01:a=0 -l | pfsout absolute.exr`

**Comment by gabrieleilertsen** [comment]
The result is very much depending on the calibration and intended setup. HDR-VDP expects calibrated pixels as input, so the images need to be scaled to approximately correspond to absolute luminance values. The intended viewing setup also influences the result, where e.g. more pixels per visual angle (more close up view) means lower score.

It could be difficult to compare results to previous evaluations without knowing the setup, but you can still use HDR-VDP for evaluating the results of different algorithms given the same evaluation setup.

**Comment by PK15946** [comment]
Got it! Thanks a lot!
