### ISSUE TITLE
The file type of image data

### ISSUE THREAD

**Issue by tgupta14** [gabrieleilertsen/hdrcnn#37]
Hi. I have a quick question. What is the file type (HDR, EXR, PNG, JPG, etc) of the input images for this project? The file type of the images that go into the virtual camera? Correct me if I am wrong, I understand that Virtual Camera creates augmented and LDR images from HDR image. My question is, what is the file type of this HDR image? Is it .HDR or .EXR or .JPG?

Also if you can outline the file types of the image at all the stages of the pipeline will also be very helpful.

**Comment by gabrieleilertsen** [comment]
I realized that I completely missed this issue. Sorry for that. I guess it is too late now, but it is correct that input is HDR data, for which the virtual camera application generates the LDR training data. The virtual camera requires EXR, but it should be possible to modify to support other HDR formats.

The virtual camera outputs HDR-LDR pairs, where LDR images are stored as JPG. It can also create varying amounts of compression in order for the reconstruction to generalize to those types of image artifacts. If the virtual camera is compiled it is possible to run the training script directly, and this will call the virtual camera if training data has to be generated.
