### ISSUE TITLE
Source is down

### ISSUE THREAD

**Issue by 8bignic8** [gabrieleilertsen/hdrcnn#38]
Hey,

I wanted to have a look at you Paper on hdrv.org/hdrcnn/, but it seems to be offline. 

greetings

**Comment by nickossaf** [comment]
Paper also is available here:
https://paperswithcode.com/paper/hdr-image-reconstruction-from-a-single

But as website don't respond I can't get pretrained model, so can you load it on github

**Comment by nickossaf** [comment]
> Hey,
> 
> I wanted to have a look at you Paper on hdrv.org/hdrcnn/, but it seems to be offline.
> 
> greetings

Paper also is available here:
https://paperswithcode.com/paper/hdr-image-reconstruction-from-a-single

But as website doesn't respond I can't get pretrained model, so can you load it on github

**Comment by gabrieleilertsen** [comment]
Hi,

Sorry for the inconvenience. The server is down, and will move to a new one at our university. For now, paper can be found externally, and trained model params are shared through OneDrive. The links for this are updated in the readme.

**Comment by supriyaarun27** [comment]
Hi! I am unable to download the model weights. Looks like the server is down?

**Comment by gabrieleilertsen** [comment]
Hi! Can you still not download model weights? The server should be online. All material is available at:
https://weber.itn.liu.se/~gabei62/hdrcnn/material/
