### ISSUE TITLE
About Video reconstruction.

### ISSUE THREAD

**Issue by liulizhou** [gabrieleilertsen/hdrcnn#39]
Hi, 
I am trying to reconstruct the videos. you provide the parameters about video reconstruction, but I have not found relevant code about regularization loss. Can you provide some train code about video reconstruction ? thanks.

**Comment by gabrieleilertsen** [comment]
Hi! The code for training with the regularization is minimal. There is a code example in the [supplementary material](https://openaccess.thecvf.com/content_CVPR_2019/supplemental/Eilertsen_Single-Frame_Regularization_for_CVPR_2019_supplemental.pdf) of the [CVPR 2019 paper](https://openaccess.thecvf.com/content_CVPR_2019/html/Eilertsen_Single-Frame_Regularization_for_Temporally_Stable_CNNs_CVPR_2019_paper.html). I have not included this in the existing training code on Github yet, but might consider this if there's interest. However, for now it should be reasonably simple to add the regularization based on the code example.

**Comment by liulizhou** [comment]
> Hi! The code for training with the regularization is minimal. There is a code example in the [supplementary material](https://openaccess.thecvf.com/content_CVPR_2019/supplemental/Eilertsen_Single-Frame_Regularization_for_CVPR_2019_supplemental.pdf) of the [CVPR 2019 paper](https://openaccess.thecvf.com/content_CVPR_2019/html/Eilertsen_Single-Frame_Regularization_for_Temporally_Stable_CNNs_CVPR_2019_paper.html). I have not included this in the existing training code on Github yet, but might consider this if there's interest. However, for now it should be reasonably simple to add the regularization based on the code example.

Thanks.
