### ISSUE TITLE
Training code folder/ vgg16_places365_weights.npy cannot be downloaded.

### ISSUE THREAD

**Issue by weiwang90** [gabrieleilertsen/hdrcnn#40]
Hi Gabrie ,
In the training  code folder, the link for vgg 16 parameter  vgg16_places365_weights.npy  is down. Would you give a new download link?
I really like your introducing your method like reproduction procedures in the camera.  
Looking forward to your new work.

**Comment by gabrieleilertsen** [comment]
Hi! Yes, the server is down. I updated the links to parameters in the main readme, but forgot about the training code folder. I will update the links there too. All the different parameters can be accessed [here](https://liuonline-my.sharepoint.com/:f:/g/personal/gabei62_liu_se/EgyyGbSNr_5Ni-KEagejf0ABC8_w2WaQqO1IDvQZojtODQ?e=7as0J6) on OneDrive.

**Comment by weiwang90** [comment]
> Hi! Yes, the server is down. I updated the links to parameters in the main readme, but forgot about the training code folder. I will update the links there too. All the different parameters can be accessed [here](https://liuonline-my.sharepoint.com/:f:/g/personal/gabei62_liu_se/EgyyGbSNr_5Ni-KEagejf0ABC8_w2WaQqO1IDvQZojtODQ?e=7as0J6) on OneDrive.

Thanks so much for your really quick reply.
