### ISSUE TITLE
hdrcnn_params_compr_regularized.npz cannot be download.

### ISSUE THREAD

**Issue by liulizhou** [gabrieleilertsen/hdrcnn#41]
Hi, 
I want to test your model for video reconstruction, but the link for hdrcnn_params_compr_regularized.npz is down. Would you provide new download links for hdrcnn_params_compr_regularized.npz or hdrcnn_params_regularized.npz ?
thanks!

**Comment by gabrieleilertsen** [comment]
Hi! I will update the link to the regularized parameters. Had some problems finding these after the server went down, but now all different parameters are available [here](https://liuonline-my.sharepoint.com/:f:/g/personal/gabei62_liu_se/EgyyGbSNr_5Ni-KEagejf0ABC8_w2WaQqO1IDvQZojtODQ?e=7as0J6).

**Comment by liulizhou** [comment]
> Hi! I will update the link to the regularized parameters. Had some problems finding these after the server went down, but now all different parameters are available [here](https://liuonline-my.sharepoint.com/:f:/g/personal/gabei62_liu_se/EgyyGbSNr_5Ni-KEagejf0ABC8_w2WaQqO1IDvQZojtODQ?e=7as0J6).

Thanks so much.
