### ISSUE TITLE
Requirements file?

### ISSUE THREAD

**Issue by rleaver152** [gabrieleilertsen/hdrcnn#48]
Is there any possibility of a requirements.txt file (non gpu tensor flow) 

I'm trying every conceivable combination of 1.x  tensorflow, tensorlayer, wrapt and numpy etc but cannot get pip to find a working package version combination between them all.   Python3.6 and 3.7 both failing.     If there's a working requirements.txt file that could be generated,  that would be great!!

**Comment by gabrieleilertsen** [comment]
Hi. It seems like it's starting to be a bit of a challenge with the requirements for tensorflow 1 code. It would probably be a good idea to update the code to tensorflow 2, but I haven't been able to find the time for it yet. I'm currently running the scripts with:

tensorflow-gpu  1.15.0
tensorlayer  1.11.1
wrapt  1.12.1
python 3.6

The problem here is that tensorflow 1.15.0 depends on wrapt>=1.11.1, while tensorlayer 1.11.1 depends on wrapt<1.11 and >=1.10. However, I it is still possible to run tensorflow with wrapt 1.10, or tensorlayer with wrapt 1.12.1. For this to work, you could for example install tensorlayer first, with wrapt 1.10, and then tensorflow, which will update wrapt to 1.12.1.

I think this will make it problematic to have a requirements file for installing the necessary dependencies, but I hope the above information can help you.

**Comment by rleaver152** [comment]
Hi 

Very many thanks and appreciated

**Comment by rleaver152** [comment]
Hi

Warnings of

WARNING:tensorflow:From hdrcnn_predict.py:108: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

Network setup:
WARNING:tensorflow:From /Users/richard_leaver/Scripts/PythonEnvironments/hdrcnn-venv/lib/python3.6/site-packages/tensorlayer/layers/core.py:131: The name tf.get_variable_scope is deprecated. Please use tf.compat.v1.get_variable_scope instead.

WARNING:tensorflow:From /Users/richard_leaver/Scripts/PythonEnvironments/hdrcnn-venv/lib/python3.6/site-packages/tensorlayer/layers/convolution/expert_conv.py:201: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /Users/richard_leaver/Scripts/PythonEnvironments/hdrcnn-venv/lib/python3.6/site-packages/tensorlayer/layers/convolution/expert_conv.py:202: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From /Users/richard_leaver/Scripts/PythonBuilds/hdrcnn/network.py:285: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /Users/richard_leaver/Scripts/PythonBuilds/hdrcnn/network.py:237: The name tf.log is deprecated. Please use tf.math.log instead.

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From hdrcnn_predict.py:118: The name tf.InteractiveSession is deprecated. Please use tf.compat.v1.InteractiveSession instead.

___________________



Then sadly its failing with 

"Loading trained parameters from 'hdrcnn_params.npz'...Traceback (most recent call last):
  File "hdrcnn_predict.py", line 122, in <module>
    load_params = tl.files.load_npz(name=FLAGS.params)
  File "/Users/richard_leaver/Scripts/PythonEnvironments/hdrcnn-venv/lib/python3.6/site-packages/tensorlayer/files/utils.py", line 1645, in load_npz
    return d['params']
  File "/Users/richard_leaver/Scripts/PythonEnvironments/hdrcnn-venv/lib/python3.6/site-packages/numpy/lib/npyio.py", line 255, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/Users/richard_leaver/Scripts/PythonEnvironments/hdrcnn-venv/lib/python3.6/site-packages/numpy/lib/format.py", line 727, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

“

My requirements file attached (solely to show what’s in there,  I followed your sequencing)    Grateful if you would consider generating one from your side and I can compare the two in case some obvious change I can make.

best
Richard


Package              Version
-------------------- ---------
absl-py              0.12.0
astor                0.8.1
cached-property      1.5.2
certifi              2020.12.5
chardet              3.0.4
cloudpickle          1.6.0
cycler               0.10.0
decorator            4.4.2
gast                 0.2.2
google-pasta         0.2.0
grpcio               1.36.1
h5py                 3.1.0
idna                 2.7
imageio              2.4.1
importlib-metadata   3.7.3
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.2
kiwisolver           1.3.1
lxml                 4.2.6
Markdown             3.3.4
matplotlib           3.0.3
networkx             2.5
numpy                1.19.5
OpenEXR              1.3.2
opt-einsum           3.3.0
Pillow               8.1.2
pip                  21.0.1
progressbar2         3.38.0
protobuf             3.15.6
pyparsing            2.4.7
python-dateutil      2.8.1
python-utils         2.5.6
PyWavelets           1.1.1
requests             2.20.1
scikit-image         0.14.5
scikit-learn         0.20.4
scipy                1.1.0
setuptools           54.2.0
six                  1.15.0
tensorboard          1.15.0
tensorflow           1.15.0
tensorflow-estimator 1.15.1
tensorlayer          1.11.1
termcolor            1.1.0
tqdm                 4.28.1
typing-extensions    3.7.4.3
urllib3              1.24.3
Werkzeug             1.0.1
wheel                0.36.2
wrapt                1.12.1
zipp                 3.4.1

**Comment by rleaver152** [comment]
Had problems but looking like pip install numpy==1.16.2  is working  alongside your earlier solutions.
