### ISSUE TITLE
Regularization code for the existing code

### ISSUE THREAD

**Issue by abhishri-medewar** [gabrieleilertsen/hdrcnn#54]
I have been working on implementing the regularization code by using the following document **https://computergraphics.on.liu.se/temporally_stable_cnns/material/cvpr2019_supplementary.pdf** as my reference. I am not able to understand which part of the training code(hdrcnn_train.py) should I add the following: Tfx = tf.contrib.image.transform(fx, T, interpolation = ’BILINEAR ’ ) ?? Any help would be appreciated.

**Comment by gabrieleilertsen** [comment]
Hi. Sorry for the late reply. Here is an example of integrating the regularization in the training code:
[hdrcnn_train.py.zip](https://github.com/gabrieleilertsen/hdrcnn/files/9870867/hdrcnn_train.py.zip)

On line 103-106 you can select what type of regularization, and which strength to use.

**Comment by abhishri-medewar** [comment]
Hi, 
Thank you for your reply. What data was used to verify the performance of the regularization method to check if it actually reduces the flicker issue?

**Comment by gabrieleilertsen** [comment]
Please have a look at the [paper](https://openaccess.thecvf.com/content_CVPR_2019/html/Eilertsen_Single-Frame_Regularization_for_Temporally_Stable_CNNs_CVPR_2019_paper.html) for specification of the datasets used. There were multiple experiments on colorization and single-image HDR reconstruction.
