### ISSUE TITLE
network.py Line 247 error

### ISSUE THREAD

**Issue by dikzhang** [gabrieleilertsen/hdrcnn#6]
network.py Line 247 error ,need delete labels:
      ` network = tl.layers.ConcatLayer([input_layer,skip_layer], 3, '%s/skip_connection'%str)`

Traceback (most recent call last):
  File "hdrcnn_predict.py", line 112, in <module>
    net = network.model(x)
  File "/home/ubuntu/hdrcnn/hdrcnn/network.py", line 63, in model
    network = decoder(network, skip_layers, batch_size, is_training)
  File "/home/ubuntu/hdrcnn/hdrcnn/network.py", line 144, in decoder
    network = skip_connection_layer(network, skip_layers[5], 'decoder/h2/fuse_skip_connection', is_training)
  File "/home/ubuntu/hdrcnn/hdrcnn/network.py", line 247, in skip_connection_layer
    network = tl.layers.ConcatLayer(layer = [input_layer,skip_layer], concat_dim=3, name ='%s/skip_connection'%str)
TypeError: __init__() got an unexpected keyword argument 'layer'

**Comment by gabrieleilertsen** [comment]
It seems like 'layer' has been replaced by 'layers' in the latest version of TensorLayer. I have deleted the label as you suggested, which should work in both new and older versions of TensorLayer.

Thanks for pointing out the problem!
