### ISSUE TITLE
does this method support reconstruction from dark images

### ISSUE THREAD

**Issue by guoyejun** [gabrieleilertsen/hdrcnn#8]
Hi,

I just found this great paper and start reading. Will try the code after the reading.

As far as I understand, the reconstruction is to build more details from both the bright image parts and the dark image parts. But in the second paragraph of INTRODUCTION of this paper, it only mentions the 'bright image parts, such as highlights, lost due to saturation of the camera sensor'. It gives me the sense that the image dark parts are not supported. It it right? thanks

**Comment by gabrieleilertsen** [comment]
Yes, that is correct. The method focuses on only the saturated image areas. The final result is a blend between linearized input image in darker areas, and reconstructed information close to saturated image areas. By focusing on saturated pixels, we can allow for better quality, and this information is the most important when transforming an LDR image to HDR.

**Comment by guoyejun** [comment]
got it, thanks  for the reply!
